FROM node:20-alpine

WORKDIR /usr/app/back

# RUN apk add --no-cache postgresql-client # For testing
RUN npm install -g pnpm

# Copy the app folder to the container
COPY . .

# Install the dependencies and generate the Prisma client
RUN pnpm install --prod
RUN pnpm build
RUN pnpm prisma generate

EXPOSE 3000

CMD ["pnpm", "run", "start:prod"]
