FROM node:20-alpine

WORKDIR /usr/app/back

# RUN apk add --no-cache postgresql-client # For testing
RUN npm install -g pnpm
RUN npm install -g @nestjs/cli

# Copy the app folder to the container
COPY . .

# Install the dependencies and generate the Prisma client
RUN pnpm install
RUN pnpm prisma generate
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "run", "start:prod"]
