FROM node:20-alpine

WORKDIR /usr/app/front

# RUN apk add --no-cache postgresql-client # For testing
RUN npm install -g pnpm
RUN npm install -g typescript

# Copy the app folder to the container
COPY . .

# Remove the dist and node_modules folders
RUN rm -rf node_modules

# Install the dependencies
RUN pnpm install
RUN pnpm run build

EXPOSE 8080

CMD ["pnpm", "run", "start"]
